// Vue2_/calculator/src/components/Button.vue
<template>
  <button class="button"
    :class="{ double, triple, operation }">
      {{ label }}
  </button>
</template>

<script>
export default {
    props: {
        label: {},
        operation: { type: Boolean },
        double: { type: Boolean },
        triple: { type: Boolean }
    }
}
</script>

<style>
:root{
    
}
</style>

// react/calc/src/components/Button.jsx
import React from "react";
import './Button.css'

export default props => {
    let classes = 'button '
    classes += props.operation ? 'operation' : ''
    classes += props.double ? 'double' : ''
    classes += props.triple ? 'triple' : ''
    return (
        <button onClick={e => props.click && props.click(props.label)} className={classes}>
            {props.label}
        </button>
    )
}
